builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./cmd/proxy/main.go
    binary: athens-proxy
    env:
      - CGO_ENABLED=0
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - license*
  - LICENSE*
  - readme*
  - README*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
