global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'testunit'
      static_configs:
        - targets: ['testunit']
    - job_name: 'teste2e'
      static_configs:
        - targets: ['teste2e']
    - job_name: 'athens-proxy'
      static_configs:
          - targets: ['athens-proxy:3000']
      
