version: 2.1
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          command: |
            shellcheck -x test/e2e-kind.sh
          
  lint-install-charts:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.3.3
      K8S_VERSION: v1.14.2
      KIND_VERSION: v0.3.0
    steps:
      - checkout
      - run:
          command: test/e2e-kind.sh
          no_output_timeout: 3600
          
workflows:
  version: 2
  lint_and_install:
    jobs:
      - lint-scripts
      - lint-install-charts:
          requires:
            - lint-scripts
