name: Build docs
on:
  push:
  workflow_dispatch: # Allow this task to be manually started (you'll never know)

jobs:
  build-docs:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.1'

      - name: Build site
        shell: bash
        run: |
          hugo --gc --minify --source ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
