name: Publish Build Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        id: install-go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download
        if: steps.install-go.outputs.cache-hit != 'true'

      - name: Capture Current Date
        id: date
        run: echo "::set-output name=date::$(date -u '+%Y-%m-%d-%H:%M:%S-%Z')"

      - name: Release with goreleaser
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7.2.1
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          DATE: ${{ steps.date.outputs.date }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
